### ISSUE TITLE
{{ascending}} not working for pages?

### ISSUE THREAD

**Issue by KeyvanJS** [olegp/mcms#13]
This is my first time using this so i could be doing something wrong.

I created three page which i can access via url.

when I add 

<pre>
{{ascending}} <a href="{{link}}">{{title}}</a> {{/ascending}}</pre> to the index.html file i get this:

<pre>[object Object],[object Object],[object Object] {{/ascending}}</pre>

on the rendered page.

**Comment by olegp** [comment]
What happens when you add the hash:

```
 {{#ascending}} {{title}} {{/ascending}}
```

See the "enumerable sections" in https://github.com/janl/mustache.js#readme

**Comment by KeyvanJS** [comment]
Yup that works! Thanks!

**Comment by olegp** [comment]
Thanks for the report, I've fixed the README.

**Comment by acao** [comment]
FYI - the README is correct, but the pages/index.md file is still missing the hash!  All for the better on my end.. just learned a lot about mustache :)

**Comment by olegp** [comment]
My bad, index.md is just a symlink to README.md on my machine, but Git doesn't do symlinks & I didn't realize I should add it separately. Will fix.
